### PR TITLE
Add card components

### PR DESCRIPTION
**Pull request by adidoesnt**

### CODE REVIEW

**Comment by ninest** [comment]
So you're fetching from https://api.nusmods.com/v2/2021-2022/moduleInfo.json for the module/courses info. Do you think we should make functions and abstract this out? Rather than fetching directly in the component, perhaps something like

```
fetchAllModules() => List of modules
fetchModule('CODE') => info on one module
```

**Comment by ninest** [comment]
Also, have you ever used [React Query](https://react-query.tanstack.com/)?

**Comment by adidoesnt** [comment]
> So you're fetching from https://api.nusmods.com/v2/2021-2022/moduleInfo.json for the module/courses info. Do you think we should make functions and abstract this out? Rather than fetching directly in the component, perhaps something like
> 
> ```
> fetchAllModules() => List of modules
> fetchModule('CODE') => info on one module
> ```

Yeah this would make sense for sure - I'll work on that once we get the actual ModuleCards to render? there's still an issue with those if you don't mind taking a look

**Comment by adidoesnt** [comment]
> Also, have you ever used [React Query](https://react-query.tanstack.com/)?

briefly, yes - what's up?

**Comment by ninest** [comment]
So it seems like the modules were a list of objects. The console also said `PayloadTooLargeError: request entity too large`. Seems to be related to https://github.com/expo/expo-cli/issues/3896 (`console.log`ing a message that's too big)

I changed it from `Object.entries(modules).forEach((entry) => {` to `modules.map((entry) => {` because it seems modules is a list. I've left the previous code there in case you need to make changes

**Review by ninest — COMMENTED** [review]
Issue has mostly been fixed 👍

Had to return ModuleCard

**Pull request merged**
