### PR TITLE
Services and database schema

### PR DESCRIPTION
**Pull request by ninest**
The `Repository` classes will be to access the database directly while the `Service` classes contain the methods we will call in the app.

### CODE REVIEW

**Comment by ninest** [comment]
I did want to ask though, are there differences between student and tutor in terms of their fields?

```
model Student {
  userId String @id @unique
  user   User   @relation(fields: [userId], references: [id])

  // A student can have many assignments
  assignments Assignment[]
}

model Tutor {
  user   User   @relation(fields: [userId], references: [id])
  userId String @id @unique

  // A tutor can have many assignments
  assignments Assignment[]
}
```

**Comment by ninest** [comment]
Also, in the schema, you have put the comment `change this to a relation`. Should I change them>

**Comment by ninest** [comment]
Removed some redundant fields in assignment because we can access them from `assignment.tutor.` or `assignment.student.`

**Comment by ninest** [comment]
I'm currently working on seeding. Relevant documentation:

- https://www.prisma.io/docs/concepts/components/prisma-schema/relations
- https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations
- https://www.prisma.io/docs/concepts/components/prisma-schema/relations/one-to-one-relations
- https://www.prisma.io/docs/concepts/components/prisma-schema/relations/one-to-many-relations

**Comment by ninest** [comment]
@adidoesnt Added some more seeding. When you edit the seed script, run `npm run db:reset`. It will reset the current database, make the migrations, and run the seeding script. If you want to view the database in a nice GUI, run `npm run db:studio`

**Comment by adidoesnt** [comment]
> @adidoesnt Added some more seeding. When you edit the seed script, run `npm run db:reset`. It will reset the current database, make the migrations, and run the seeding script. If you want to view the database in a nice GUI, run `npm run db:studio`.
> 
> See the `seed.js` file for examples on relations and `connect` with Prisma

Understood, thank you @ninest :)

**Review by adidoesnt — APPROVED** [review]
merging in order to continue work

**Pull request merged**
